/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoa;

import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;


/**
 *
 * @author diego-lopez
 */
public class CargarUsuarios extends javax.swing.JFrame {
    
    JFileChooser fileChooser = new JFileChooser();


    /**
     * Creates new form CargarUsuarios
     */
    public CargarUsuarios() {
        initComponents();
        pintarTabla();
        
    }
    
    private void pintarTabla() {
        
        String encabezado[] = {"Nombre","Password" , "Rol" , "Usuario" , "Estado"};
        DefaultTableModel t = new DefaultTableModel(encabezado, ProyectoFinal.usuarios.size());
        jTableCargarUsuarios.setModel(t);
        TableModel tabla = jTableCargarUsuarios.getModel();

        for(int i = 0; i < ProyectoFinal.usuarios.size();i++) {
            Usuario u = ProyectoFinal.usuarios.get(i);
            tabla.setValueAt(u.nombre, i, 0);
            tabla.setValueAt(u.password, i, 1);
            tabla.setValueAt(u.rol, i, 2);
            tabla.setValueAt(u.usuario, i, 3); 
            tabla.setValueAt(u.estado, i, 4); 

        }                
    } 
    
    public void leerXML(String path) {
        
        try {
            DocumentBuilderFactory constructor = DocumentBuilderFactory.newInstance();
            DocumentBuilder lector = constructor.newDocumentBuilder();
            
            Document document = lector.parse(new File(path));
            document.getDocumentElement().normalize();
            
            NodeList nodos = document.getElementsByTagName("usuario");
            
            for(int i = 0; i < nodos.getLength(); i ++)
            {
                Node nodo = nodos.item(i);
                
                if(nodo.getNodeType() == Node.ELEMENT_NODE)
                {
                    Usuario u = new Usuario();
                    
                    Element elemento = (Element) nodo;
                    u.nombre = elemento.getElementsByTagName("nombre").item(0).getTextContent();
                    u.password = elemento.getElementsByTagName("contraseña").item(0).getTextContent();
                    u.rol = elemento.getElementsByTagName("rol").item(0).getTextContent();
                    u.usuario = elemento.getElementsByTagName("idusuario").item(0).getTextContent();
                    
                    if(u.rol.equalsIgnoreCase("Administrador")) {
                        u.rol = "A";
                    }else {
                        u.rol = "V";
                    }
                    
                    u.estado = "Activo";
                    
                    ProyectoFinal.usuarios.add(u);
                    pintarTabla();                    
                }
            }
            
        } catch (Exception ex) {
            Logger.getLogger(CargarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCargarUsuarios = new javax.swing.JTable();
        jButtonCargar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableCargarUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCargarUsuarios);

        jButtonCargar.setText("Cargar");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButtonCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonCargar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
        Usuario u = new Usuario();
        File nombreArchivo;
        this.fileChooser.setDialogTitle("Busque el archivo");
        int option = this.fileChooser.showOpenDialog(this);

        if(option == JFileChooser.APPROVE_OPTION) {

            nombreArchivo = this.fileChooser.getSelectedFile();
            System.out.print( nombreArchivo.getAbsoluteFile());
            leerXML(nombreArchivo.getAbsoluteFile().toString());
        }

    }//GEN-LAST:event_jButtonCargarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCargarUsuarios;
    // End of variables declaration//GEN-END:variables
}
