/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoa;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author diego-lopez
 */
public class CargarCupon extends javax.swing.JFrame {
    
    JFileChooser fileChooser = new JFileChooser();
    

    /**
     * Creates new form CargarCupon
     */
    public CargarCupon() {
        initComponents();
        pintarTabla();
    }
    
    private void pintarTabla() {
        
        String encabezado[] = {"Codigo descuento","Descuento" , "Tipo descuento" , "Fecha de vencimiento"};
        DefaultTableModel t = new DefaultTableModel(encabezado, ProyectoFinal.cupones.size());
        jTableCupones.setModel(t);
        TableModel tabla = jTableCupones.getModel();

        for(int i = 0; i < ProyectoFinal.cupones.size();i++) {
            Cupon c = ProyectoFinal.cupones.get(i);
            tabla.setValueAt(c.codigo_descuento, i, 0);
            tabla.setValueAt(c.descuento, i, 1);
            tabla.setValueAt(c.tipo_descuento, i, 2);
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            tabla.setValueAt(formato.format(c.fecha_de_vencimiento), i, 3); 
        }                
    }    
    
    public void leer(String ruta)
    {
        try {
            File archivo = new File(ruta);
            FileReader leer = new FileReader(archivo);
            BufferedReader bloque = new BufferedReader(leer);
            String linea = bloque.readLine();
            while( linea != null && linea.length() > 10 )
            {
                String[] cupon = linea.split("\\|");
                Cupon c = new Cupon();
                c.codigo_descuento = cupon[0].trim();
                c.descuento = Integer.parseInt(cupon[1].trim());
                c.tipo_descuento = cupon[2].trim();
                String fecha = (cupon[3].trim());
                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                c.fecha_de_vencimiento = formato.parse(fecha);
                                
                ProyectoFinal.cupones.add(c);
                linea = bloque.readLine();
                pintarTabla();
            }
            leer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CargarCupon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) { 
            Logger.getLogger(CargarCupon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CargarCupon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCupones = new javax.swing.JTable();
        jButtonCargar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableCupones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCupones);

        jButtonCargar.setText("Cargar");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCargar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonCargar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
        Cupon c = new Cupon();
        File nombreArchivo;
        this.fileChooser.setDialogTitle("Busque el archivo");
        int option = this.fileChooser.showOpenDialog(this); 
        
        if(option == JFileChooser.APPROVE_OPTION) {
            
           nombreArchivo = this.fileChooser.getSelectedFile();
           System.out.print( nombreArchivo.getAbsoluteFile());
           leer(nombreArchivo.getAbsoluteFile().toString());

        }
        
    }//GEN-LAST:event_jButtonCargarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCupones;
    // End of variables declaration//GEN-END:variables
}
