/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoa;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author diego-lopez
 */
public class ConsultaCupon extends javax.swing.JFrame {
    
        private Cupon cupon;


    /**
     * Creates new form ConsultaCupon
     */
    public ConsultaCupon() {
        initComponents();
        pintarTabla();
        
        jComboBoxTipoDescuento.removeAllItems();
        jComboBoxTipoDescuento.addItem("Monto");
        jComboBoxTipoDescuento.addItem("Porcentaje");

    }
    
    private void pintarTabla() {
        
        String encabezado[] = {"Codigo descuento","Descuento" , "Tipo descuento" , "Fecha de vencimiento"};
        DefaultTableModel t = new DefaultTableModel(encabezado, ProyectoFinal.cupones.size());
        jTableCupones.setModel(t);
        TableModel tabla = jTableCupones.getModel();

        for(int i = 0; i < ProyectoFinal.cupones.size();i++) {
            Cupon c = ProyectoFinal.cupones.get(i);
            tabla.setValueAt(c.codigo_descuento, i, 0);
            tabla.setValueAt(c.descuento, i, 1);
            tabla.setValueAt(c.tipo_descuento, i, 2);
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            tabla.setValueAt(formato.format(c.fecha_de_vencimiento), i, 3);
        }                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCupones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigoDescuento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDescuento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFechaVencimiento = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jComboBoxTipoDescuento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableCupones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCupones);

        jLabel1.setText("Codigo descuento:");

        jLabel2.setText("Descuento:");

        jLabel3.setText("Tipo descuento:");

        jLabel4.setText("Fecha vencimiento:");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jComboBoxTipoDescuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigoDescuento)
                            .addComponent(jTextFieldDescuento)
                            .addComponent(jTextFieldFechaVencimiento)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButtonGuardar)
                                .addGap(0, 24, Short.MAX_VALUE))
                            .addComponent(jComboBoxTipoDescuento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addComponent(jButtonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalir)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBoxTipoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        if( cupon != null ){

            if( jTextFieldCodigoDescuento.getText().isEmpty() == false )
            {
                cupon.codigo_descuento = jTextFieldCodigoDescuento.getText();
            }else{
                JOptionPane.showMessageDialog(this, "Codigo de descuento vacio vacio!!!");
                return;
            }

            if( jTextFieldDescuento.getText().isEmpty() == false ) {

                cupon.descuento = Integer.parseInt(jTextFieldDescuento.getText());

            }else {
                JOptionPane.showMessageDialog(this, "Descuento vacio!!!");
                return;
            }

            cupon.tipo_descuento = jComboBoxTipoDescuento.getSelectedItem().toString();

            if( jTextFieldFechaVencimiento.getText().isEmpty()== false){

                String fecha = jTextFieldFechaVencimiento.getText();
                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                try {
                    cupon.fecha_de_vencimiento = formato.parse(fecha);
                } catch (ParseException ex) {
                    Logger.getLogger(ConsultaCupon.class.getName()).log(Level.SEVERE, null, ex);
                }

            }else {
                JOptionPane.showMessageDialog(this, "Fecha vacio!!!");
                return;
            }

            pintarTabla();
            JOptionPane.showMessageDialog(this, "Cupon modificado exitosamente");
            jTextFieldCodigoDescuento.setText("");
            jTextFieldDescuento.setText("");
            jComboBoxTipoDescuento.setSelectedIndex(-1);
            jTextFieldFechaVencimiento.setText("");   
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        jTableCupones.getSelectedRow();

        int eliminar = jTableCupones.getSelectedRow();

        if(eliminar <=  0 ){

            if(JOptionPane.showConfirmDialog(this, "Esta seguro de elimar")== 0)
            {
                ProyectoFinal.cupones.remove((eliminar));
                pintarTabla();

            }

        }else {

            JOptionPane.showMessageDialog(this, "Seleccione un cupon valido para elimirar");

        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        if(jTableCupones.getSelectedRow()>=0){

            cupon = ProyectoFinal.cupones.get(jTableCupones.getSelectedRow());
            jTextFieldCodigoDescuento.setText(cupon.codigo_descuento);
            jTextFieldDescuento.setText( Integer.toString(cupon.descuento));

            if(cupon.tipo_descuento.equals("Monto"))
            {
                jComboBoxTipoDescuento.setSelectedIndex(0);

            }else {

                jComboBoxTipoDescuento.setSelectedIndex(1);
            }
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            jTextFieldFechaVencimiento.setText( formato.format(cupon.fecha_de_vencimiento));

        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxTipoDescuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCupones;
    private javax.swing.JTextField jTextFieldCodigoDescuento;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldFechaVencimiento;
    // End of variables declaration//GEN-END:variables
}
