/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoa;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author diego-lopez
 */
public class ConsultarVentas extends javax.swing.JFrame {
    
        JFileChooser fileChooser = new JFileChooser();
        
        String contenidoExportar;


    /**
     * Creates new form ConsultarVentas
     */
    public ConsultarVentas() {
        initComponents();
        pintarTabla();
        
    }
    
    public  void escribir(String ruta, String contenido){
        try {
            FileWriter archivo = new FileWriter(ruta);
            PrintWriter escribir = new PrintWriter(archivo);
            escribir.write(contenido);
            escribir.close();
            archivo.close();
        } catch (IOException ex) {
            Logger.getLogger(ConsultarVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void pintarTabla() 
    {
        this.contenidoExportar = "";
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        
        String encabezado[] = {"Nombre cliente","Nit" , "Direccion" , "Total" , "Total sin iva" , "Descuento", "Vendedor" , "Fecha"};
        DefaultTableModel t = new DefaultTableModel(encabezado, ProyectoFinal.ventas.size());
        jTableConsultarVentas.setModel(t);
        TableModel tabla = jTableConsultarVentas.getModel();

        for( int i = 0; i < ProyectoFinal.ventas.size(); i++ ) 
        {
            Venta v = ProyectoFinal.ventas.get(i);
            tabla.setValueAt(v.nombrecliente, i, 0);
            tabla.setValueAt(v.nit, i, 1);
            tabla.setValueAt(v.direccioncliente, i, 2);
            tabla.setValueAt(v.total.toString().formatted("%.-2f"), i, 3);
            tabla.setValueAt(v.totalsiniva.toString().formatted("%.-2f"), i, 4);
            tabla.setValueAt(v.descuento, i, 5);
            tabla.setValueAt(v.empleado, i, 6);
            tabla.setValueAt(v.fecha.getTime().toString(), i, 7);
            String fechaFormateada = formato.format(v.fecha.getTime());
            
            this.contenidoExportar += v.nombrecliente + "," 
                    + v.nit + "," 
                    + v.direccioncliente + "," 
                    + v.total + "," 
                    + v.totalsiniva + "," 
                    + v.descuento + "," 
                    + v.empleado + "," 
                    + fechaFormateada
                    + "\n";
            
        } 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultarVentas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableConsultarVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableConsultarVentas);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonExportar.setText("Exportar");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonExportar))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        
        File nombreArchivo;
        this.fileChooser.setDialogTitle("Busque el archivo");
        int option = this.fileChooser.showOpenDialog(this); 
        
        if(option == JFileChooser.APPROVE_OPTION) {
            
           nombreArchivo = this.fileChooser.getSelectedFile();
           this.escribir(nombreArchivo.toString(), this.contenidoExportar);

        }        
    }//GEN-LAST:event_jButtonExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultarVentas;
    // End of variables declaration//GEN-END:variables
}
