/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoa;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author diego-lopez
 */
public class InformeLibros extends javax.swing.JFrame {
    
    JFileChooser fileChooser = new JFileChooser();

    String contenidoExportar;


    /**
     * Creates new form InformeLibros
     */
    public InformeLibros() {
        initComponents();
        pintarTabla();
    }
    
    public  void escribir(String ruta, String contenido){
        try {
            FileWriter archivo = new FileWriter(ruta);
            PrintWriter escribir = new PrintWriter(archivo);
            escribir.write(contenido);
            escribir.close();
            archivo.close();
        } catch (IOException ex) {
            Logger.getLogger(ConsultarVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void pintarTabla() 
    {
        this.contenidoExportar = "";
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        
        String encabezado[] = {"Fecha de Venta","Cantidad" , "Titulo" , "Precio"};
        DefaultTableModel t = new DefaultTableModel(encabezado, ProyectoFinal.libroventa.size());
        jTableinformeLibros.setModel(t);
        TableModel tabla = jTableinformeLibros.getModel();

        for( int i = 0; i < ProyectoFinal.libroventa.size(); i++ ) 
        {
            LibroVenta lv = ProyectoFinal.libroventa.get(i);
            String fechaFormateada = formato.format(lv.fecha_venta.getTime());
            tabla.setValueAt(fechaFormateada, i, 0);
            tabla.setValueAt(lv.cantidad, i, 1);
            tabla.setValueAt(lv.librotitulo, i, 2);
            tabla.setValueAt(lv.subtotal, i, 3);
            
            this.contenidoExportar += fechaFormateada + "," 
                    + lv.cantidad+ "," 
                    + lv.librotitulo + "," 
                    + lv.subtotal 
                    + "\n";
            
        } 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableinformeLibros = new javax.swing.JTable();
        jButtonExportar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableinformeLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableinformeLibros);

        jButtonExportar.setText("Exportar");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonExportar))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed

        File nombreArchivo;
        this.fileChooser.setDialogTitle("Elija el archivo a exportar");
        int option = this.fileChooser.showOpenDialog(this);

        if(option == JFileChooser.APPROVE_OPTION) {

            nombreArchivo = this.fileChooser.getSelectedFile();
            this.escribir(nombreArchivo.toString(), this.contenidoExportar);

        }
    }//GEN-LAST:event_jButtonExportarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();     
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableinformeLibros;
    // End of variables declaration//GEN-END:variables
}
