/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoa;

import javax.swing.JOptionPane;

/**
 *
 * @author diego-lopez
 */
public class UsuarioNuevo extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioNuevo
     */
    public UsuarioNuevo() 
    {
        initComponents();
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Administrador");
        jComboBox1.addItem("Vendedor");

        jComboBoxEstado.removeAllItems();
        jComboBoxEstado.addItem("Activo");
        jComboBoxEstado.addItem("Inactivo");
        jComboBoxEstado.addItem("Eliminado");
        jComboBoxEstado.setSelectedIndex(-1);

    }
    
    public boolean LargoPassword(String password)
    {
        final int LARGO_MINIMO_PASSWORD = 6;
        
        if( password.length() >= LARGO_MINIMO_PASSWORD ) // validacion del tamaño del password
        {
            return true;
            
        }else {
            
            JOptionPane.showMessageDialog(rootPane, "¡Password debe tener al menos " + LARGO_MINIMO_PASSWORD + " caracteres!");
            return false;
        }
    }
    
    public boolean CantidadMinusculasPassword( String password )
    {
        final int CANTIDAD_MINUSCULAS   = 1;
         
        int minusculas = 0;
   
        for( int i = 0; i < password.length(); i++ )
        {
            if( Character.isLowerCase(password.charAt(i) ) == true )
            {
                minusculas++;
            }
        }

        // validacion de las mayusculas
        if( minusculas >= CANTIDAD_MINUSCULAS ) 
        {

            return true;

        }else {

            JOptionPane.showMessageDialog(this, "¡Password debe  tener al menos " + CANTIDAD_MINUSCULAS + " minuscula(s)! ");
            return false;
        }        
    }

    public boolean CantidadMayusculasPassword( String password )
    {
        final int CANTIDAD_MAYUSCULAS   = 1;
         
        int mayusculas = 0;
   
        for( int i = 0; i < password.length(); i++ )
        {
            if( Character.isUpperCase( password.charAt(i) ) == true )
            {
                mayusculas++;
            }
        }

        // validacion de las mayusculas
        if( mayusculas >= CANTIDAD_MAYUSCULAS ) 
        {

            return true;

        }else {

            JOptionPane.showMessageDialog(this, "¡Password debe  tener al menos " + CANTIDAD_MAYUSCULAS + " mayuscula(s)! ");
            return false;
        }        
    }
    public boolean CantidadNumerosPassword( String password )
    {
        final int CANTIDAD_NUMEROS   = 1;
         
        int numeros = 0;
   
        for( int i = 0; i < password.length(); i++ )
        {
            if( Character.isDigit(password.charAt(i) ) == true )
            {
                numeros++;
            }
        }

        // validacion de los numeros
        if( numeros >= CANTIDAD_NUMEROS ) 
        {

            return true;

        }else {

            JOptionPane.showMessageDialog(this, "¡Password debe  tener al menos " + CANTIDAD_NUMEROS + " numero(s)! ");
            return false;
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextfieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextfieldPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextfieldUsuario = new javax.swing.JTextField();
        jBottonCrear = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jLabel1.setText("Nombre:");

        jTextfieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextfieldNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        jLabel3.setText("Usuario:");

        jBottonCrear.setText("Crear");
        jBottonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBottonCrearActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado:");

        jLabel5.setText("Rol:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextfieldNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextfieldUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(jTextfieldPassword)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jBottonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextfieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextfieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextfieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBottonCrear)
                    .addComponent(jButtonSalir))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBottonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBottonCrearActionPerformed
        Usuario u = new Usuario();
        
        if( jTextfieldNombre.getText().isEmpty() == false )
        {
            u.nombre = jTextfieldNombre.getText();
        }else{
            JOptionPane.showMessageDialog(this, "Nombre vacio!!!");
            return;
        }
        
        if( jTextfieldPassword.getText().isEmpty() == false ) {
            
            u.password = jTextfieldPassword.getText();

        }else {
            JOptionPane.showMessageDialog(this, "Password vacio!!!");
            return;
        }
        
        if( jTextfieldUsuario.getText().isEmpty() == false) {
            
            u.usuario = jTextfieldUsuario.getText();

        }else {
            
            JOptionPane.showMessageDialog(this, "Usuario vacio!!!");
            return;
        }

        String rol = jComboBox1.getSelectedItem().toString();
        
        if(rol.equals("Administrador"))
        {
            u.rol = "A";
            
        }else {
            u.rol = "V";
        }
        
        u.estado = jComboBoxEstado.getSelectedItem().toString();
        
        if( LargoPassword(u.password) == true 
                && CantidadMayusculasPassword( u.password ) == true 
                && CantidadMinusculasPassword(u.password) == true  
                && CantidadNumerosPassword(u.password ) == true)
        {
        
            ProyectoFinal.usuarios.add(u);
        
            // Agregar funcion contraseña con una mayuscula y minimo 6 caracteres
        
            JOptionPane.showMessageDialog(this, "Usuario creado exitosamente");
        }
    }//GEN-LAST:event_jBottonCrearActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
            this.dispose();

    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextfieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextfieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextfieldNombreActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBottonCrear;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextfieldNombre;
    private javax.swing.JTextField jTextfieldPassword;
    private javax.swing.JTextField jTextfieldUsuario;
    // End of variables declaration//GEN-END:variables
}
